name: PR health check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check the project
      uses: actions/setup-node@v1
      with:
        node-version: '17.2.0'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: 'Build'
      run: docker build . --file Dockerfile --tag ulisesgascon/github-backup:latest
      